"""add fans and genres tables

Revision ID: 88858ec7b614
Revises: 76dd42d5fd52
Create Date: 2023-05-15 14:32:57.668903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88858ec7b614'
down_revision = '76dd42d5fd52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avg_bpm', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('prodominent_instrument', sa.String(), nullable=True),
    sa.Column('commonly_known', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'reviews', 'fans', ['fan_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_table('genres')
    op.drop_table('fans')
    # ### end Alembic commands ###
